### ISSUE TITLE
skin opacity % and size suggestion

### ISSUE THREAD

**Issue by Thunder33345** [SalmonDE/RestrictedSkins#1]
allow owner to set the minimum % opacity of the skin allowed

and also minimum/maximum "size" of geometry
to prevent mega/mini/very small skins

**Comment by SalmonDE** [comment]
I reckon a geometry size validation to be more complex than I intended this plugin to be. So I'll be closing this now.

**Comment by Thunder33345** [comment]
is it okay if i remake another issue for LONGTERM?

**Comment by SalmonDE** [comment]
@Thunder33345 sure, go ahead
