### ISSUE TITLE
Could not load

### ISSUE THREAD

**Issue by artulloss** [SalmonDE/RestrictedSkins#5]
Recent update makes this plugin not load

**Comment by SalmonDE** [comment]
Could you give me some more details? I can‘t reproduce this.

**Comment by SalmonDE** [comment]
Did you enable the gd extension in your php binaries?

**Comment by artulloss** [comment]
I checked the extensions I have enabled in my bianaries and gd is enabled. I tried this on my test server and just says could not load.. I'll look some more.

**Comment by artulloss** [comment]
Yea it's the extension lol

**Comment by artulloss** [comment]
Can you help me though, I tried php -m in the bin folder like in this post https://forums.pmmp.io/threads/enable-gd-extension-in-linux-php.5803/
and it lists gd extension, yet it says could not load extension.

**Comment by SalmonDE** [comment]
Try what muqsit posted in that thread and recompile your binaries using the [compile.sh script ](https://github.com/pmmp/php-build-scripts/blob/master/compile.sh).

**Comment by artulloss** [comment]
Thanks, got it to work!
