### ISSUE TITLE
Make like an allowed geometry folder ?

### ISSUE THREAD

**Issue by artulloss** [SalmonDE/RestrictedSkins#6]
Idk how you could do this but I think it would be neat, like allow wing skins if you wanted or capes too ect

**Comment by SalmonDE** [comment]
This should be done in a different plugin. RestrictedSkins only takes actions when skins are applied by the player, therefore this can be easily done in an external plugin where you can choose between geometry, skins and capes.

**Comment by artulloss** [comment]
Kind of thinking the same, but I don't want them to choose it I just want them to be able to use a cape skin if they want ect just no small skins
