### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by TheWalkingDrift** [SalmonDE/RestrictedSkins#7]
I've Download Thema Plugin today Front poggit bitte Ich can't Install I use Pocketmine Version 3.8.3 and the thus stays in the console:
[Server thread/ERROR]: Required extension gd not loaded

**Comment by SalmonDE** [comment]
Make sure you've enabled the gd extension in your php.ini file.
This is an issue with your php binaries and not the plugin.
The following forums.pmmp.io threads might help you:

- https://forums.pmmp.io/threads/gd-on-php.6532/
- https://forums.pmmp.io/threads/error-call-to-undefined-function-boss-imagecreatefrompng-exception-in-plugins-bossjg-master.8002/
- https://forums.pmmp.io/threads/required-extension-gd2-not-loaded.6911/
